### ISSUE TITLE
Change the colors

### ISSUE THREAD

**Issue by larsenwork** [kennethormandy/opentype-feature-bundle#1]
In many themes the `feature xxxx` are very similar in color - maybe feature should be colourless?  

![screen shot 2015-06-17 at 23 40 39](https://cloud.githubusercontent.com/assets/3859425/8219428/51c59738-154a-11e5-9fb4-3d2b9504283b.png)

`Sub` + `by` belong together in my mind so they could/should be the same color.

**Comment by kennethormandy** [comment]
Hey! You’ll have to open this one on [the original repo](https://github.com/brew/opentype-feature-bundle) for this one. I had thought you meant the issue was Atom-specific. I don’t impose any opinions about this part of the project, it’s a straight port of the Textmate version that needs to be in a separate repo.

If you open a pull request on the original project or an update is made there, I will pull in the change here. :)
